### ISSUE TITLE
Zeile 134: curl: Befehl nicht gefunden ERROR mdadm not installed!

### ISSUE THREAD

**Issue by littlesteve01** [007revad/Synology_Recover_Data#32]
i tried to use your script and followed all the steps and the ISO you linked an get the following error:

"Zeile 134: curl: Befehl nicht gefunden ERROR mdadm not installed!"

manuall installation of mdadm also is not working

**Comment by 007revad** [comment]
After the script sets Ubuntu to get an older version of mdadm that works with DSM's superblock location apt-get won't install mdadm. So for installing mdadm the script uses `apt install -y mdadm`
